"""
Git Manager for Kroosybul AI
Handles automatic Git repository initialization, commits, and version control.
"""

import os
import subprocess
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any
from datetime import datetime


class GitManager:
    """Manages Git operations for generated projects"""

    def __init__(self):
        """Initialize the Git manager"""
        self.default_gitignore = {
            'python': [
                '__pycache__/',
                '*.py[cod]',
                '*$py.class',
                '*.so',
                '.Python',
                'build/',
                'develop-eggs/',
                'dist/',
                'downloads/',
                'eggs/',
                '.eggs/',
                'lib/',
                'lib64/',
                'parts/',
                'sdist/',
                'var/',
                'wheels/',
                '*.egg-info/',
                '.installed.cfg',
                '*.egg',
                'MANIFEST',
                '.venv/',
                'venv/',
                'ENV/',
                'env/',
                '.pytest_cache/',
                '.coverage',
                'htmlcov/',
                '*.log',
                '.env',
                '.DS_Store'
            ],
            'javascript': [
                'node_modules/',
                'npm-debug.log*',
                'yarn-debug.log*',
                'yarn-error.log*',
                '.npm',
                '.eslintcache',
                '.node_repl_history',
                '*.tgz',
                '.yarn-integrity',
                '.env',
                '.env.local',
                '.env.development.local',
                '.env.test.local',
                '.env.production.local',
                'dist/',
                'build/',
                '.DS_Store',
                'coverage/',
                '.vscode/',
                '.idea/'
            ],
            'typescript': [
                'node_modules/',
                'dist/',
                'build/',
                '*.js',
                '*.js.map',
                '*.d.ts',
                'npm-debug.log*',
                'yarn-debug.log*',
                'yarn-error.log*',
                '.env',
                'coverage/',
                '.DS_Store',
                '.vscode/',
                '.idea/'
            ],
            'java': [
                '*.class',
                '*.log',
                '*.jar',
                '*.war',
                '*.ear',
                '*.zip',
                '*.tar.gz',
                '*.rar',
                'target/',
                '.classpath',
                '.project',
                '.settings/',
                'bin/',
                '.DS_Store'
            ],
            'rust': [
                'target/',
                'Cargo.lock',
                '**/*.rs.bk',
                '*.pdb',
                '.DS_Store'
            ],
            'go': [
                '*.exe',
                '*.exe~',
                '*.dll',
                '*.so',
                '*.dylib',
                '*.test',
                '*.out',
                'vendor/',
                '.DS_Store'
            ]
        }

    def init_repository(self, project_path: str, language: str = 'python') -> Tuple[bool, str]:
        """Initialize a Git repository for a project

        Args:
            project_path: Path to the project directory
            language: Programming language for gitignore template

        Returns:
            Tuple of (success, message)
        """
        try:
            # Check if already a git repo
            git_dir = os.path.join(project_path, '.git')
            if os.path.exists(git_dir):
                return True, "Git repository already initialized"

            # Initialize repository
            result = subprocess.run(
                ['git', 'init'],
                cwd=project_path,
                capture_output=True,
                text=True,
                timeout=30
            )

            if result.returncode != 0:
                return False, f"Failed to initialize Git: {result.stderr}"

            # Create .gitignore
            gitignore_path = os.path.join(project_path, '.gitignore')
            if not os.path.exists(gitignore_path):
                self._create_gitignore(project_path, language)

            # Configure user if not set
            self._configure_git_user(project_path)

            # Initial commit
            self.commit_changes(
                project_path,
                "Initial commit - Project generated by Kroosybul AI",
                add_all=True
            )

            return True, "Git repository initialized successfully"
        except Exception as e:
            return False, f"Error initializing Git repository: {str(e)}"

    def _create_gitignore(self, project_path: str, language: str):
        """Create a .gitignore file for the project"""
        gitignore_content = self.default_gitignore.get(
            language,
            self.default_gitignore['python']
        )

        gitignore_path = os.path.join(project_path, '.gitignore')
        with open(gitignore_path, 'w') as f:
            f.write('# Generated by Kroosybul AI\n\n')
            f.write('\n'.join(gitignore_content))
            f.write('\n')

    def _configure_git_user(self, project_path: str):
        """Configure Git user if not already set"""
        try:
            # Check if user.name is set
            result = subprocess.run(
                ['git', 'config', 'user.name'],
                cwd=project_path,
                capture_output=True,
                text=True,
                timeout=10
            )

            if not result.stdout.strip():
                # Set default user
                subprocess.run(
                    ['git', 'config', 'user.name', 'Kroosybul AI'],
                    cwd=project_path,
                    timeout=10
                )

            # Check if user.email is set
            result = subprocess.run(
                ['git', 'config', 'user.email'],
                cwd=project_path,
                capture_output=True,
                text=True,
                timeout=10
            )

            if not result.stdout.strip():
                # Set default email
                subprocess.run(
                    ['git', 'config', 'user.email', 'kroosybul@ai.generated'],
                    cwd=project_path,
                    timeout=10
                )
        except Exception:
            pass  # Not critical if this fails

    def commit_changes(self, project_path: str, message: str,
                      add_all: bool = True, files: Optional[List[str]] = None) -> Tuple[bool, str]:
        """Commit changes to the repository

        Args:
            project_path: Path to the project directory
            message: Commit message
            add_all: Whether to add all changes
            files: Specific files to add (if add_all is False)

        Returns:
            Tuple of (success, message)
        """
        try:
            # Add files
            if add_all:
                result = subprocess.run(
                    ['git', 'add', '-A'],
                    cwd=project_path,
                    capture_output=True,
                    text=True,
                    timeout=30
                )
            elif files:
                result = subprocess.run(
                    ['git', 'add'] + files,
                    cwd=project_path,
                    capture_output=True,
                    text=True,
                    timeout=30
                )
            else:
                return False, "No files specified to add"

            if result.returncode != 0:
                return False, f"Failed to add files: {result.stderr}"

            # Check if there are changes to commit
            result = subprocess.run(
                ['git', 'diff', '--cached', '--quiet'],
                cwd=project_path,
                timeout=30
            )

            # If return code is 0, there are no changes
            if result.returncode == 0:
                return True, "No changes to commit"

            # Commit
            result = subprocess.run(
                ['git', 'commit', '-m', message],
                cwd=project_path,
                capture_output=True,
                text=True,
                timeout=30
            )

            if result.returncode == 0:
                return True, f"Changes committed: {message}"
            else:
                return False, f"Failed to commit: {result.stderr}"
        except Exception as e:
            return False, f"Error committing changes: {str(e)}"

    def commit_iteration(self, project_path: str, iteration_number: int,
                        description: str) -> Tuple[bool, str]:
        """Commit an iteration/refinement of the project

        Args:
            project_path: Path to the project directory
            iteration_number: The iteration number
            description: Description of changes

        Returns:
            Tuple of (success, message)
        """
        message = f"Iteration {iteration_number}: {description}"
        return self.commit_changes(project_path, message, add_all=True)

    def get_commit_history(self, project_path: str, limit: int = 10) -> List[Dict[str, str]]:
        """Get commit history

        Args:
            project_path: Path to the project directory
            limit: Maximum number of commits to return

        Returns:
            List of commit dictionaries
        """
        try:
            result = subprocess.run(
                ['git', 'log', f'-{limit}', '--pretty=format:%H|%an|%ae|%ad|%s'],
                cwd=project_path,
                capture_output=True,
                text=True,
                timeout=30
            )

            if result.returncode != 0:
                return []

            commits = []
            for line in result.stdout.strip().split('\n'):
                if line:
                    parts = line.split('|')
                    if len(parts) == 5:
                        commits.append({
                            'hash': parts[0],
                            'author': parts[1],
                            'email': parts[2],
                            'date': parts[3],
                            'message': parts[4]
                        })

            return commits
        except Exception as e:
            print(f"Error getting commit history: {e}")
            return []

    def rollback_to_commit(self, project_path: str, commit_hash: str) -> Tuple[bool, str]:
        """Rollback to a specific commit

        Args:
            project_path: Path to the project directory
            commit_hash: Hash of the commit to rollback to

        Returns:
            Tuple of (success, message)
        """
        try:
            # First, check if there are uncommitted changes
            result = subprocess.run(
                ['git', 'status', '--porcelain'],
                cwd=project_path,
                capture_output=True,
                text=True,
                timeout=30
            )

            if result.stdout.strip():
                return False, "Cannot rollback: uncommitted changes present. Commit or stash them first."

            # Reset to commit
            result = subprocess.run(
                ['git', 'reset', '--hard', commit_hash],
                cwd=project_path,
                capture_output=True,
                text=True,
                timeout=30
            )

            if result.returncode == 0:
                return True, f"Successfully rolled back to commit {commit_hash[:7]}"
            else:
                return False, f"Failed to rollback: {result.stderr}"
        except Exception as e:
            return False, f"Error rolling back: {str(e)}"

    def create_branch(self, project_path: str, branch_name: str) -> Tuple[bool, str]:
        """Create a new branch

        Args:
            project_path: Path to the project directory
            branch_name: Name of the new branch

        Returns:
            Tuple of (success, message)
        """
        try:
            result = subprocess.run(
                ['git', 'checkout', '-b', branch_name],
                cwd=project_path,
                capture_output=True,
                text=True,
                timeout=30
            )

            if result.returncode == 0:
                return True, f"Created and switched to branch '{branch_name}'"
            else:
                return False, f"Failed to create branch: {result.stderr}"
        except Exception as e:
            return False, f"Error creating branch: {str(e)}"

    def list_branches(self, project_path: str) -> List[str]:
        """List all branches

        Args:
            project_path: Path to the project directory

        Returns:
            List of branch names
        """
        try:
            result = subprocess.run(
                ['git', 'branch'],
                cwd=project_path,
                capture_output=True,
                text=True,
                timeout=30
            )

            if result.returncode == 0:
                branches = []
                for line in result.stdout.strip().split('\n'):
                    # Remove leading * and whitespace
                    branch = line.strip().lstrip('* ')
                    if branch:
                        branches.append(branch)
                return branches
            else:
                return []
        except Exception:
            return []

    def get_current_branch(self, project_path: str) -> Optional[str]:
        """Get the current branch name

        Args:
            project_path: Path to the project directory

        Returns:
            Current branch name or None
        """
        try:
            result = subprocess.run(
                ['git', 'rev-parse', '--abbrev-ref', 'HEAD'],
                cwd=project_path,
                capture_output=True,
                text=True,
                timeout=30
            )

            if result.returncode == 0:
                return result.stdout.strip()
            else:
                return None
        except Exception:
            return None

    def get_diff(self, project_path: str, commit1: Optional[str] = None,
                 commit2: Optional[str] = None) -> str:
        """Get diff between commits or working directory

        Args:
            project_path: Path to the project directory
            commit1: First commit hash (None for working directory)
            commit2: Second commit hash (None for HEAD)

        Returns:
            Diff output
        """
        try:
            if commit1 and commit2:
                cmd = ['git', 'diff', commit1, commit2]
            elif commit1:
                cmd = ['git', 'diff', commit1]
            else:
                cmd = ['git', 'diff']

            result = subprocess.run(
                cmd,
                cwd=project_path,
                capture_output=True,
                text=True,
                timeout=30
            )

            if result.returncode == 0:
                return result.stdout
            else:
                return ""
        except Exception:
            return ""

    def get_status(self, project_path: str) -> Dict[str, Any]:
        """Get repository status

        Args:
            project_path: Path to the project directory

        Returns:
            Dictionary with status information
        """
        try:
            # Get current branch
            branch = self.get_current_branch(project_path)

            # Get modified files
            result = subprocess.run(
                ['git', 'status', '--porcelain'],
                cwd=project_path,
                capture_output=True,
                text=True,
                timeout=30
            )

            modified_files = []
            if result.returncode == 0:
                for line in result.stdout.strip().split('\n'):
                    if line:
                        status = line[:2]
                        filename = line[3:]
                        modified_files.append({
                            'file': filename,
                            'status': status.strip()
                        })

            # Get commit count
            result = subprocess.run(
                ['git', 'rev-list', '--count', 'HEAD'],
                cwd=project_path,
                capture_output=True,
                text=True,
                timeout=30
            )

            commit_count = int(result.stdout.strip()) if result.returncode == 0 else 0

            return {
                'branch': branch,
                'modified_files': modified_files,
                'commit_count': commit_count,
                'is_clean': len(modified_files) == 0
            }
        except Exception as e:
            return {
                'branch': None,
                'modified_files': [],
                'commit_count': 0,
                'is_clean': True,
                'error': str(e)
            }
